name: yamtk-build
on: push

jobs:
  macos:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, 'build_me')
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: build
        run: make release
      - name: test
        run: make check
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'build_me')
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: build
        run: make release
      - name: test
        run: make check
  ubuntu-sanitizers:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'build_me')
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: test with sanitizers
        run: make check-debug
